version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    image: himalayy/todo-backend:latest
    container_name: todo-backend
    ports:
      - "8091:8091"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pass

  frontend:
    image: himalayy/todo-frontend:latest
    container_name: todo-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mysql_data: