services:
  mysql:
    image: mysql:8.0
    container_name: todo-mysql
    restart: always
    environment:
      MYSQL_DATABASE: todo_db
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todo_pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 30

  backend:
    image: himalayy/todo-backend:latest
    container_name: todo-backend
    restart: always
    ports:
      - "8091:8091"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      # ✅ MUST use service name + 3306
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/todo_db?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: todo_user
      SPRING_DATASOURCE_PASSWORD: todo_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_DATASOURCE_HIKARI_INITIALIZATION_FAIL_TIMEOUT: 0

  frontend:
    image: himalayy/todo-frontend:latest
    container_name: todo-frontend
    restart: always
    ports:
      - "3001:80"
    depends_on:
      - backend

volumes:
  mysql_data:
